Extra space

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -2,7 +2,7 @@ name: CI
 
 on:
   push:
-    branches: [main]
+    branches: ["main"]
   pull_request:
 
 jobs:
@@ -15,41 +15,42 @@ jobs:
 
       - name: Show tree (debug)
         run: |
-         pwd
-         ls -la
-         find release-keeper -maxdepth 3 -type f -print
-         
+          pwd
+          ls -la
+          find release-keeper -maxdepth 3 -type f -print
+
       - name: Bash syntax check (deploy.sh)
         run: |
           bash -n release-keeper/deploy/deploy.sh
-        
-        - name: Smoke deploy (success path)
-         run: |
-         set -e
-         mkdir -p /tmp/src
-         echo "OK VERSION" > /tmp/src/index.html
 
-         mkdir -p /tmp/deploy_root
-         release-keeper/deploy/deploy.sh release /tmp/src /tmp/deploy_root
+      - name: Smoke deploy (success path)
+        run: |
+          set -e
+          mkdir -p /tmp/src
+          echo "OK VERSION" > /tmp/src/index.html
 
-         echo "Current point to:"
-         readlink /tmp/deploy_root/current
-         echo "Current content:"
-         cat /tmp/deploy_root/current/index.html
+          mkdir -p /tmp/deploy_root
+          release-keeper/deploy/deploy.sh release /tmp/src /tmp/deploy_root
 
-        - name: Fail deploy + verify rollback (fail path)
-         run: |
-            set -e
-            echo "BROKEN VERSION" > /tmp/src/index.html
+          echo "Current points to:"
+          readlink /tmp/deploy_root/current
 
-          #IMPORTANT: we EXPECT failure here, but we watn to continue to check rollback
+          echo "Current content:"
+          cat /tmp/deploy_root/current/index.html
+
+      - name: Fail deploy + verify rollback (fail path)
+        run: |
+          set -e
+          echo "BROKEN VERSION" > /tmp/src/index.html
+
+          # EXPECT failure, but continue to verify rollback
           set +e
           FAIL_AFTER_SWITCH=1 release-keeper/deploy/deploy.sh release /tmp/src /tmp/deploy_root
           rc=$?
           set -e
 
           echo "exit_code=$rc"
-          if [[ $rc -eq 0 ]];then
+          if [[ $rc -eq 0 ]]; then
             echo "Expected failure but got success"
             exit 1
           fi
